;;; load-set-font.el --- load my fonts.
;;
;; Copyright (C) 2018 Suk
;;
;; Author: Suk
;;
;; This file is not part of GNU Emacs.
;;
;; This program is free software; you can redistribute it and/or
;; modify it under the terms of the GNU General Public License as
;; published by the Free Software Foundation; either version 2, or
;; (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
;; General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program; see the file COPYING.  If not, write to
;; the Free Software Foundation, Inc., 51 Franklin Street, Fifth
;; Floor, Boston, MA 02110-1301, USA.
;;
;;; Commentary:
;; Fonts Setting
;;
;;; Code:
;;; --------------------fonts--------------------------------
;;; we using cnfonts
;;; ---------------------------------------------------------

;; Auto generated by cnfonts
;; <https://github.com/tumashu/cnfonts>
;; (set-face-attribute
;;  'default nil
;;  :font (font-spec :name "-outline-Victor Mono-bold-italic-normal-mono-*-*-*-*-c-*-iso10646-1"
;;                   :weight 'normal
;;                   :slant 'normal
;;                   :size 12.5))
;; (dolist (charset '(kana han symbol cjk-misc bopomofo))
;;   (set-fontset-font
;;    (frame-parameter nil 'font)
;;    charset
;;    (font-spec :name "-outline-宋体-normal-normal-normal-*-*-*-*-*-p-*-iso10646-1"
;;               :weight 'normal
;;               :slant 'normal
;;               :size 16.5)))

;; 默认用宋体
;; (dolist (charset '(kana han symbol cjk-misc bopomofo))
;;   (set-fontset-font (frame-parameter nil 'font)
;;                     charset
;;                     (font-spec :family "Simsun" :size 12)))

;; 设置不同字符集使用不同的字体
;;(set-face-attribute 'default' nil :font "Migu 1M Less:pixelsize=16")
;; (set-frame-font "Migu 1M Less-12")
;; (set-fontset-font (frame-parameter nil 'font) 'han '("Simsun" . "unicode-bmp"))
;; (set-fontset-font (frame-parameter nil 'font) 'symbol '("Console" . "unicode-bmp"))
;; (set-fontset-font (frame-parameter nil 'font) 'japanese-jisx0208 '("Meiryo" ."unicode-bmp"))

(eval-when-compile
  (require '+const)
  (require '+custom))

;;===================================================
;; Fonts
;;===================================================
;;;###autoload
(defun suk-install-fonts ()
  "Install necessary fonts."
  (interactive)
  (all-the-icons-install-fonts)
  (nerd-icons-install-fonts))

;; 解决卡顿
(setq inhibit-compacting-font-caches t)
;;只渲染当前屏幕语法高亮，加快显示速度
(setq font-lock-maximum-decoration t)
(global-font-lock-mode t)
(setq font-lock-maximum-size 15000000); set 5mb file size limit for fontification
;; Fonts
(when (or sys/mac-x-p sys/linux-x-p)
  (set-frame-font "Noto Sans CJK SC-12"))

;;(setq en-font "Consolas Mono"
;;      cn-font "宋体")
(setq emacs-font-size-pair '(28 . 32))
(setq en-font "victor Mono"
      cn-font "LXGW WenKai Mono")
(cond
  ((member "Victor Mono" (font-family-list))
    (setq en-font "Victor Mono"))
  ((member "JetBrains Mono" (font-family-list))
    (setq en-font "JetBrains Mono"))
  ((member "Migu 1M Less" (font-family-list))
    (setq en-font "Migu 1M Less"))
  ((member "Source Code Pro" (font-family-list))
    (setq en-font "Source Code Pro"))
  ((member "Monaco" (font-family-list))
    (setq en-font "Monaco"))
  ((member "DejaVu Sans Mono" (font-family-list))
    (setq en-font "DejaVu Sans Mono"))
  ((member "Consolas" (font-family-list))
    (setq en-font "Consolas"))
)
(cond
  ((member "KleeOne+CJK" (font-family-list))
    (setq en-font "KleeOne+CJK"))
  ((member "LXGW WenKai" (font-family-list))
    (setq en-font "LXGW WenKai"))
  ((member "露鹜文楷" (font-family-list))
    (setq en-font "露鹜文楷"))
  ((member "LXGW WenKai Mono" (font-family-list))
   (setq en-font "LXGW WenKai Mono"))
  ((member "露鹜文楷等宽" (font-family-list))
   (setq en-font "露鹜文楷等宽"))
  ((member "仓耳今楷01-27533 W04" (font-family-list))
    (setq cn-font "仓耳今楷01-27533 W04"))
  ((member "Sarasa Mono SC" (font-family-list))
    (setq cn-font "Sarasa Mono SC"))
  ((member "Simsun" (font-family-list))
    (setq cn-font "Simsun"))
  ((member "宋体" (font-family-list))
    (setq cn-font "宋体"))
  ((member "微软雅黑" (font-family-list))
    (setq cn-font "微软雅黑"))
)

(setq en-font-size (car emacs-font-size-pair)
      cn-font-size (cdr emacs-font-size-pair))

(defun config-font-size (en-size cn-size)
  (set-face-attribute 'default nil :font (format "%s:pixelsize=%d" en-font en-size))
  ;; DEFAULT
  ;;(set-face-attribute 'default nil :height 100 :family en-font)

  ;; LATIN
  (set-fontset-font (frame-parameter nil 'font) 'unicode en-font)
  ;;(set-frame-font (format "%s-%s" en-font en-size))
  ;; (set-frame-font "Sarasa Mono SC-10" t)
  ;;(add-to-list 'default-frame-alist '(font .  (format "%s-%s" en-font en-size)))

  ;; CJK
  (if (display-graphic-p)
      (dolist (charset '(kana han cjk-misc bopomofo))
        (set-fontset-font (frame-parameter nil 'font) charset
                          (font-spec :family cn-font :size cn-size)))))
;; (config-font-size 17 18)
(config-font-size (default-value 'en-font-size) (default-value 'cn-font-size))

(defvar emacs-english-font nil
  "The font name of English.")

(defvar emacs-cjk-font nil
  "The font name for CJK.")
(defvar emacs-font-size-pair nil
  "Default font size pair for (latin . cjk).")

(defun font-exist-p (fontname)
  "Test if this FONTNAME is exist or not."
  (if (or (not fontname) (string= fontname ""))
      nil
    (if (not (x-list-fonts fontname))
        nil t)))

(defun set-font (latin cjk size-pair)
  "Setup Emacs LATIN and CJK fonts with SIZE-PAIR on x window-system."
  (when (font-exist-p latin)
      (set-frame-font (format "%s:pixelsize=%d" latin (car size-pair)) t))

  (when (font-exist-p cjk)
      (dolist (charset '(kana han symbol cjk-misc bopomofo))
        (set-fontset-font (frame-parameter nil 'font) charset
                          (font-spec :family cjk :size (cdr size-pair))))))

(defun emacs-step-font-size (step)
  "Increase/Decrease Emacs's font by STEP size."
  (let ((scale-steps emacs-font-size-pair-list))
    (if (< step 0) (setq scale-steps (reverse scale-steps)))
    (setq emacs-font-size-pair
          (or (cadr (member emacs-font-size-pair scale-steps))
              emacs-font-size-pair))
    (when emacs-font-size-pair
      (message "emacs font size set to %.1f" (car emacs-font-size-pair))
      (set-font emacs-english-font emacs-cjk-font emacs-font-size-pair))))

(defun increase-emacs-font-size ()
  "Decrease Emacs's font-size acording emacs-font-size-pair-list."
  (interactive) (emacs-step-font-size 1))

(defun decrease-emacs-font-size ()
  "Increase Emacs's font-size acording emacs-font-size-pair-list."
  (interactive) (emacs-step-font-size -1))

(when (member "Symbols Nerd Font Mono" (font-family-list))
  (set-fontset-font t 'symbol "Symbols Nerd Font Mono")
  ;; FontAwesome 范围
  (set-fontset-font t '(#xf000 . #xf2e0) "Symbols Nerd Font Mono")
  ;; 扩展至可能包含 Material Design Icons 的范围
  (set-fontset-font t '(#xe000 . #xf8ff) "Symbols Nerd Font Mono"))


(when sys/win32p
  ;; (set-frame-font "Simsun 12")
  ;; setup change size font, base on emacs-font-size-pair-list
  (global-set-key (kbd "C-M-=") 'increase-emacs-font-size)
  (global-set-key (kbd "C-M--") 'decrease-emacs-font-size)
  (setq emacs-english-font en-font)
  (setq emacs-cjk-font cn-font)
  ;; Setup font size based on emacs-font-size-pair
  (set-font emacs-english-font emacs-cjk-font emacs-font-size-pair)
)


;;(when (and suk-cnfonts (display-graphic-p))
;;  ;; cnfonts doesn't support terminal
;;  (use-package cnfonts
;;    :hook (after-init . cnfonts-enable)
;;    :config
;;    ;; NOTE: on macOS, the frame size is changed during the startup without below.
;;    ;; Keep frame size
;;    (setq cnfonts-keep-frame-size nil)
;;    (add-hook 'window-setup-hook
;;              (lambda ()
;;                (setq cnfonts-keep-frame-size t)))
;;
;;    ;; Set profiles
;;    (setq cnfonts-use-cache t)
;;    (setq cnfonts-profiles
;;          '("program" "org-mode" "read-book"))
;;    (setq cnfonts--profiles-steps '(("program-normal" . 4)
;;                                    ("org-mode" . 6)
;;                                    ("read-book" . 9)))))


;;----------------------------------------------------------
(defun load-program-font ()
  "Load Program font."
  (interactive)
  ;; 设置英文字体并指定字号。
  ;;(set-face-attribute 'default nil :font "Migu 1M Less 11")
  ;;(set-face-attribute 'default nil :font "Victor Mono Medium 12")
  (set-face-attribute 'default nil :height 140 :family "LXGW WenKai Mono 12")

  (cond
   ;; linnux 下不支持
   ((member "Victor Mono" (font-family-list))
    (set-face-attribute 'default nil :font "Victor Mono 10")
    (set-frame-font "Victor Mono-10" t)
    (add-to-list 'default-frame-alist '(font . "Victor Mono-10"))
    (set-fontset-font (frame-parameter nil 'font) 'unicode "Victor Mono"))
   ((member "JetBrains Mono" (font-family-list))
    (set-face-attribute 'default nil :font "JetBrains Mono 10")
    (set-frame-font "JetBrains Mono-10" t)
    (add-to-list 'default-frame-alist '(font . "JetBrains Mono-10"))
    (set-fontset-font (frame-parameter nil 'font) 'unicode "Jetbrains"))
   ;; 这个字体偏小
   ;;((member "monofur" (font-family-list))
   ;; (set-face-attribute 'default nil :font "monofur"))
   ((member "Migu 1M Less" (font-family-list))
    (set-face-attribute 'default nil :font "Migu 1M Less 10")
    (set-frame-font "Migu 1M Less-10" t)
    (add-to-list 'default-frame-alist '(font . "Migu 1M Less-10"))
    (set-fontset-font (frame-parameter nil 'font) 'unicode "Migu 1M Less"))
   ((member "Source Code Pro" (font-family-list))
    (set-face-attribute 'default nil :font "Source Code Pro 10")
    (set-frame-font "Source Code Pro-10" t)
    (add-to-list 'default-frame-alist '(font . "Source Code Pro-10"))
    (set-fontset-font (frame-parameter nil 'font) 'unicode "Source Code Pro"))
   ((member "Monaco" (font-family-list))
    (set-face-attribute 'default nil :font "Monaco 10")
    (set-frame-font "Monaco-10" t)
    (add-to-list 'default-frame-alist '(font . "Monaco-10"))
    (set-fontset-font (frame-parameter nil 'font) 'unicode "Monaco"))
   ((member "DejaVu Sans Mono" (font-family-list))
    (set-face-attribute 'default nil :font "DejaVu Sans Mono")
    (set-frame-font "DejaVu Sans Mono" t)
    (add-to-list 'default-frame-alist '(font . "DejaVu Sans Mono-10"))
    (set-fontset-font (frame-parameter nil 'font) 'unicode "DejaVu Sans Mono"))

   ((member "Consolas" (font-family-list))
    (set-face-attribute 'default nil :font "Consolas 10")
    (set-frame-font "Consolas-10" t)
    (add-to-list 'default-frame-alist '(font . "Consolas-10"))
    (set-fontset-font (frame-parameter nil 'font) 'unicode "Consolas")
    )
   )
  ;; 给相应的字符集设置中文字体
  (dolist (charset '(han cjk-misc chinese-gbk))
    (cond
     ((member "KleeOne+CJK" (font-family-list))
                                        ;(set-face-attribute 'default nil :height 140 :family "KleeOne+CJK")
      (dolist (charset '(kana han symbol cjk-misc bopomofo))
        (set-fontset-font (frame-parameter nil 'font) charset (font-spec :family "KleeOne+CJK"))))
     ((member "LXGW WenKai Mono" (font-family-list))
                                        ;(set-face-attribute 'default nil :height 140 :family "LXGW WenKai Mono")
      (dolist (charset '(kana han symbol cjk-misc bopomofo))
        (set-fontset-font (frame-parameter nil 'font) charset (font-spec :family "LXGW WenKai Mono"))))
     ((member "露鹜文楷等宽" (font-family-list))
                                        ;(set-face-attribute 'default nil :height 140 :family "露鹜文楷等宽")
      (dolist (charset '(kana han symbol cjk-misc bopomofo))
        (set-fontset-font (frame-parameter nil 'font) charset (font-spec :family "露鹜文楷等宽"))))
     ((member "Sarasa Mono SC" (font-family-list))
                                        ;(set-face-attribute 'default nil :height 140 :family "Sarasa Mono SC")
      (dolist (charset '(kana han symbol cjk-misc bopomofo))
        (set-fontset-font (frame-parameter nil 'font) charset (font-spec :family "Sarasa Mono SC"))))
     ((member "仓耳今楷01-27533 W04" (font-family-list))
                                        ;(set-face-attribute 'default nil :height 140 :family "仓耳今楷01-27533 W04")
      (dolist (charset '(kana han symbol cjk-misc bopomofo))
        (set-fontset-font (frame-parameter nil 'font) charset (font-spec :family "仓耳今楷01-27533 W04"))))
     ((member "Simsun" (font-family-list))
                                        ;(set-face-attribute 'default nil :height 140 :family "Simsun")
      (dolist (charset '(kana han symbol cjk-misc bopomofo))
        (set-fontset-font (frame-parameter nil 'font) charset (font-spec :family "Simsun"))))

     ))
  (message "Set program font"))
(add-hook 'prog-mode-hook 'load-org-font)
;;----------------------------------------------------------
(defun load-default-font ()
    "Load default font setting."
    (interactive)
   ;; (load-program-font)
    (set-font emacs-english-font emacs-cjk-font emacs-font-size-pair)
     (message "set default fonts")
    )
;;----------------------------------------------------------

(defun load-org-font ()
  "Load org mode font."
  (interactive)
  (make-face 'width-font-face)
  ;; DEFAULT
  (set-face-attribute 'default nil :height 100 :family "Sarasa Mono SC")

  ;; LATIN
  (set-fontset-font (frame-parameter nil 'font) 'unicode "Sarasa Mono SC")
  ;;(set-frame-font (format "%s-%s" "Sarasa Mono SC" 10))
  (set-frame-font "Sarasa Mono SC-10" t)
  (add-to-list 'default-frame-alist '(font . "Sarasa Mono SC-10"))

  ;; CJK
  (dolist (charset '(kana han symbol cjk-misc bopomofo))
    (set-fontset-font (frame-parameter nil 'font) charset (font-spec :family "Sarasa Mono SC")))

  (setq buffer-face-mode-face 'width-font-face)
  (buffer-face-mode)
  (setq loaded-font-type 3)
  (setq-default line-spacing 5)
  (message "Set org-mode font"))
;; (with-eval-after-load 'org


;;   )
  (add-hook 'org-mode-hook 'load-org-font)
;;; ----------------------------------------------------------

;; 解决 daemon 时， 字体无效。
(when (and (fboundp 'daemonp) (daemonp))
    (add-hook 'after-make-frame-functions
              (lambda (frame)
                (with-selected-frame frame
                  (load-default-font)))))

(load-default-font)

  ;; ------------------------------------------------------
  ;; 设置不同操作系统使用不同的字体
  ;; (defun my-set-font (&optional frame)
  ;;     ;; (load-default-font)
  ;;     (with-selected-frame (or frame (selected-frame))
  ;;         (if (string-equal system-type "windows-nt")
  ;;         ;; 下面是用于Windows的配置。
  ;;         (progn
  ;;             ;; 设置英文字体并指定字号。
  ;;             ;; 因为不同操作系统下字体显示的大小不一样(DPI的问题)，所以分开设置。
  ;;             (set-face-attribute 'default nil :font "Migu 1M Less 10")
  ;;             ;; 给相应的字符集设置中文字体。
  ;;             (dolist (charset '(han cjk-misc chinese-gbk))
  ;;                 (set-fontset-font "fontset-default"
  ;;                     charset (font-spec :family "Simsun")
  ;;                 )
  ;;             )
  ;;         )
  ;;
  ;;         ;; 下面是Linux的配置，道理类似。
  ;;         (set-face-attribute 'default nil :font "Migu 1M Less-10")
  ;;         (dolist (charset '(kana han cjk-misc bopomofo))
  ;;            (set-fontset-font "fontset-default"
  ;;               charset (font-spec :name "等距更纱黑体 SC")))
  ;;         )
  ;;     )
  ;; )

  ;; 运行一下立即设置字体。
  ;; (my-set-font)
  ;; (load-default-font)


  ;; For Linux
  (global-set-key (kbd "<C-mouse-4>") 'text-scale-increase)
  (global-set-key (kbd "<C-mouse-5>") 'text-scale-decrease)

  ;; For Windows
  (global-set-key (kbd "<C-wheel-up>") 'text-scale-increase)
  (global-set-key (kbd "<C-wheel-down>") 'text-scale-decrease)

  (provide 'load-set-font)
;;; load-set-font.el ends here.

  ;;   (cond
  ;;    ((member "Source Code Pro" (font-family-list))
  ;;     (set-face-attribute 'default nil :font "Source Code Pro"))
  ;;    ((member "Menlo" (font-family-list))
  ;;     (set-face-attribute 'default nil :font "Menlo"))
  ;;    ((member "Monaco" (font-family-list))
  ;;     (set-face-attribute 'default nil :font "Monaco"))
  ;;    ((member "DejaVu Sans Mono" (font-family-list))
  ;;     (set-face-attribute 'default nil :font "DejaVu Sans Mono"))
  ;;    ((member "Consolas" (font-family-list))
  ;;     (set-face-attribute 'default nil :font "Consolas")))

  ;;   (cond
  ;;    (sys/mac-x-p
  ;;     (set-face-attribute 'default nil :height 130))
  ;;    (sys/win32p
  ;;     (set-face-attribute 'default nil :height 110)))

  ;;   ;; Specify font for all unicode characters
  ;;   (when (member "Symbola" (font-family-list))
  ;;     (set-fontset-font t 'unicode "Symbola" nil 'prepend))

  ;;   ;; Specify font for chinese characters
  ;;   (cond
  ;;    ((member "WenQuanYi Micro Hei" (font-family-list))
  ;;     (set-fontset-font t '(#x4e00 . #x9fff) "WenQuanYi Micro Hei"))
  ;;    ((member "Microsoft Yahei" (font-family-list))
  ;;     (set-fontset-font t '(#x4e00 . #x9fff) "Microsoft Yahei")))
