 ;;; Commentary: load-set-font.el --- load my fonts.


;;; Code:
;;; --------------------fonts--------------------------------
;;; we using cnfonts
;;; ---------------------------------------------------------

;; Auto generated by cnfonts
;; <https://github.com/tumashu/cnfonts>
;; (set-face-attribute
;;  'default nil
;;  :font (font-spec :name "-outline-Victor Mono-bold-italic-normal-mono-*-*-*-*-c-*-iso10646-1"
;;                   :weight 'normal
;;                   :slant 'normal
;;                   :size 12.5))
;; (dolist (charset '(kana han symbol cjk-misc bopomofo))
;;   (set-fontset-font
;;    (frame-parameter nil 'font)
;;    charset
;;    (font-spec :name "-outline-宋体-normal-normal-normal-*-*-*-*-*-p-*-iso10646-1"
;;               :weight 'normal
;;               :slant 'normal
;;               :size 16.5)))

;; 默认用宋体
;; (dolist (charset '(kana han symbol cjk-misc bopomofo))
;;   (set-fontset-font (frame-parameter nil 'font)
;;                     charset
;;                     (font-spec :family "Simsun" :size 12)))

;; 设置不同字符集使用不同的字体
;(set-face-attribute 'default' nil :font "Migu 1M Less:pixelsize=16")
;; (set-frame-font "Migu 1M Less-12")
;; (set-fontset-font (frame-parameter nil 'font) 'han '("Simsun" . "unicode-bmp"))
;; (set-fontset-font (frame-parameter nil 'font) 'symbol '("Console" . "unicode-bmp"))
;; (set-fontset-font (frame-parameter nil 'font) 'japanese-jisx0208 '("Meiryo" ."unicode-bmp"))

(eval-when-compile
  (require '+const)
  (require '+custom))

(defvar loaded-font-type 0)
(defvar loaded-font-type-num 3)

;----------------------------------------------------------
(defun load-program-font ()
  "加载开发字体。"
  (interactive)
  (when sys/linuxp
    ;; Set a default font
    ;;(set-face-attribute 'default nil :font "Victor Mono 12")
    (set-face-attribute 'default nil :font "Victor Mono Light-12");; linux
    ;;(set-face-attribute 'default nil :font "Source Code Pro"))
    ;;(set-face-attribute 'default nil :font "Menlo"))
    ;;(set-face-attribute 'default nil :font "Monaco"))
    ;;(set-face-attribute 'default nil :font "DejaVu Sans Mono"))
    ;;(set-face-attribute 'default nil :font "Consolas")))
    
    ;; Specify font for chinese characters
    (set-fontset-font (frame-parameter nil 'font) 
  		    ;;'han  '("Simsun" . "unicode-bmp"))	
  		    ;;'han  '("PMingliU" . "unicode-bmp"))
  		    ;;'han  '("AR PL UKai CN" . "unicode-bmp"))
  		    ;;'han  '("AR PL UMing CN" . "unicode-bmp"))
  		    ;;'han  '("WenQuanYi Micro Hei" . "unicode-bmp"))
  		    ;;'han  '("Microsoft Yahei" . "unicode-bmp"))
		    'han  '("Noto Sans CJK SC" . "unicode-bmp")))
  
  (when (string-equal system-type "windows-nt")
    ;; 下面是用于Windows的配置。
    (progn
      ;; 设置英文字体并指定字号。
      ;; 因为不同操作系统下字体显示的大小不一样(DPI的问题)，所以分开设置。
      (set-face-attribute 'default nil :font "Migu 1M Less 12")
      ;; 给相应的字符集设置中文字体。
      (dolist (charset '(han cjk-misc chinese-gbk))
        (set-fontset-font "fontset-default"
			  charset (font-spec :family "Simsun")
			  ))))
  
  (setq loaded-font-type 1)
  (message "Set program font")
)
;----------------------------------------------------------

(defun load-article-font ()
  "加载文章用字体。"
  (interactive)
  (set-frame-font "Times New Roman 12")
  (set-fontset-font (frame-parameter nil 'font)
            'han '("PMingliU" . "unicode-bmp"))
  (setq loaded-font-type 2)
  (setq-default line-spacing 5)
  (message "Set article fonts")
)


;----------------------------------------------------------
(defun load-default-font ()
  "加载默認字体。"
  (interactive)
  (load-program-font)
  (setq loaded-font-type 0)
  (setq-default line-spacing 1)
  (message "set default fonts")
)

;;; ----------------------------------------------------------

(with-eval-after-load 'org

	(defun load-org-font ()
	  "加载org-mode字体。"
	  (interactive)
	  (make-face 'width-font-face)
	  ;;(set-face-attribute 'width-font-face nil :font "等距更纱黑体 SC 12")
	  (set-face-attribute 'width-font-face nil :font "等距更纱黑体 SC" :size 12) ;; linux
	  (setq buffer-face-mode-face 'width-font-face)
	  (buffer-face-mode)
	  (setq loaded-font-type 3)
	  (setq-default line-spacing 5)
	  (message "設置org-mode字體")
	)
  (add-hook 'org-mode-hook 'load-org-font))
  
(defun toggle-font ()
  "toggle font between program envirement and article envirement."
  (interactive)
  (setq loaded-font-type
        (%  (1+  loaded-font-type)  loaded-font-type-num ))
  (let ((foo (buffer-name))
        (bar (buffer-size)))
    (message
     "This buffer is %s and has %d characters."
     foo bar))
  (cond ((eq loaded-font-type 0)
         (load-default-font))
        ((eq loaded-font-type 1)
         (load-program-font))
        ((eq loaded-font-type 2)
         (load-article-font))
        )
  )


;;; ----------------------------------------------------------
;;; (global-set-key (kbd "<f6>") 'toggle-font)
;;; ----------------------------------------------------------


;;; ----------------------------------------------------------

;; 解决 daemon 时， 字体无效。
(if (and (fboundp 'daemonp) (daemonp))
  (add-hook 'after-make-frame-functions
        (lambda (frame)
          (with-selected-frame frame
        (load-default-font))))
  (load-default-font))


;; ------------------------------------------------------
;; 设置不同操作系统使用不同的字体
;; (defun my-set-font (&optional frame)
;;     ;; (load-default-font)
;;     (with-selected-frame (or frame (selected-frame))
;;         (if (string-equal system-type "windows-nt")
;;         ;; 下面是用于Windows的配置。
;;         (progn
;;             ;; 设置英文字体并指定字号。
;;             ;; 因为不同操作系统下字体显示的大小不一样(DPI的问题)，所以分开设置。
;;             (set-face-attribute 'default nil :font "Migu 1M Less 12")
;;             ;; 给相应的字符集设置中文字体。
;;             (dolist (charset '(han cjk-misc chinese-gbk))
;;                 (set-fontset-font "fontset-default"
;;                     charset (font-spec :family "Simsun")
;;                 )
;;             )
;;         )
;;
;;         ;; 下面是Linux的配置，道理类似。
;;         (set-face-attribute 'default nil :font "Migu 1M Less-12")
;;         (dolist (charset '(kana han cjk-misc bopomofo))
;;            (set-fontset-font "fontset-default"
;;               charset (font-spec :name "等距更纱黑体 SC")))
;;         )
;;     )
;; )

;; 运行一下立即设置字体。
;; (my-set-font)
;; (load-default-font)


;; For Linux
(global-set-key (kbd "<C-mouse-4>") 'text-scale-increase)
(global-set-key (kbd "<C-mouse-5>") 'text-scale-decrease)

;; For Windows
(global-set-key (kbd "<C-wheel-up>") 'text-scale-increase)
(global-set-key (kbd "<C-wheel-down>") 'text-scale-decrease)

;;(eval-when-compile (require 'cl))



(provide 'load-set-font)
;;; load-set-font.el ends here.

